// <auto-generated />
namespace Contexts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_first_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_first_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201709282003096_create_first_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
