// <auto-generated />
namespace Contexts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_base : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_base));
        
        string IMigrationMetadata.Id
        {
            get { return "201709282001451_create_base"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
